- name: Check vars
  assert:
    that: ntp_server is defined
- name: Copy chrony.conf
  template:
    src: templates/chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
- name: Restart chronyd
  systemd:
    name: chronyd
    state: restarted
