---
- name: Copy firewalld conf
  copy:
    src: files/firewalld.conf
    dest: /etc/firewalld/firewalld.conf
    owner: root
    group: root
    mode: 0600
  notify: Restart firewalld
- name: Copy drop zone conf
  template:
    src: templates/drop.xml.j2
    dest: /etc/firewalld/zones/drop.xml
    owner: root
    group: root
    mode: 0644
  notify: Restart firewalld
