---
- name: Check vars
  assert:
    that:
      - fw_ports is defined
- name: Install firewalld
  package: 
    name: firewalld
- name: Start firewalld
  systemd:
    name: firewalld
    enabled: yes
    state: started
- name: Add FW Ports to DROP Zone
  firewalld:
    port: '{{ item }}'
    permanent: yes
    state: enabled
    zone: drop
  loop: '{{ fw_ports }}'
  notify: Restart firewalld
- name: Default DROP zone
  shell: firewall-cmd --set-default-zone drop
  register: zone_check
  changed_when: "'ZONE_ALREADY_SET' not in zone_check.stderr"
  notify: Restart firewalld
