---
# tasks file for roles/zabbix
- name: Check vars
  assert:
    that:
      - zabbix_server is defined
      - server_hostname is defined
- name: Add zabbix repo
  dnf:
    name: https://repo.zabbix.com/zabbix/5.4/rhel/8/x86_64/zabbix-release-5.4-1.el8.noarch.rpm
    state: present
    disable_gpg_check: yes
- name: Install zabbix-agent
  dnf:
    name: zabbix-agent
    state: present
- name: Configure zabbix agent
  template:
    src: templates/zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: 0644 
- name: Restart zabbix-agent
  systemd:
    name: zabbix-agent
    state: restarted
    enabled: yes

