- name: Ensure modules are set
  assert:
    that:
      - selinux_modules is defined
- name: Install dependencies
  package:
    name:
      - setroubleshoot-server
      - setools-console
- name: Set permissive
  selinux:
    policy: targeted
    state: permissive
  register: set_enforced
- name: Autolabel
  file:
    path: /.autorelabel
    state: touch
  when: set_enforced.changed
- name: Force reboot
  reboot:
  when: set_enforced.changed
- name: Copy modules
  copy:
    src: files/{{ item }}.te
    dest: /tmp/{{ item }}.te
    owner: root
    group: root
    mode: 0600
  loop: '{{ selinux_modules }}'
- name: Compile modules
  shell: checkmodule -M -m -o /tmp/{{ item }}.mod /tmp/{{ item }}.te
  loop: '{{ selinux_modules }}'
- name: Build Policies
  shell: semodule_package -o /tmp/{{ item }}.pp -m /tmp/{{ item }}.mod
  loop: '{{ selinux_modules }}'
- name: Load module
  shell: semodule -i /tmp/{{ item }}.pp
  loop: '{{ selinux_modules }}'
- name: Clean up modules
  find:
    paths: /tmp/
    recurse: no
    patterns: ".*(pp|te|mod)$"
    use_regex: true
  register: clean_modules
- name: Remove modules files
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ clean_modules.files }}"
- name: Ensure enforcing
  selinux:
    policy: targeted
    state: enforcing
  when: set_enforced.changed
  notify: Reboot Server
