---
# tasks file for roles/zabbix
- name: Check vars
  assert:
    that:
      - zabbix_server is defined
      - server_hostname is defined
- name: Add zabbix repo
  dnf:
    name: https://repo.zabbix.com/zabbix/5.4/rhel/8/x86_64/zabbix-release-5.4-1.el8.noarch.rpm
    state: present
    disable_gpg_check: yes
- name: Install zabbix-agent
  dnf:
    name: zabbix-agent
    state: present
- name: Generate PSK
  shell: 'openssl rand -hex 32 > /etc/zabbix/zabbix_agentd.psk'
- name: Set perms PSK
  file:
    path: /etc/zabbix/zabbix_agentd.psk
    owner: zabbix
    group: root
    mode: 0600
- name: Configure zabbix agent
  template:
    src: templates/zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: 0644 
  notify: Restart zabbix-agent
- name: Enable zabbix-agent
  systemd:
    name: zabbix-agent
    state: started
    enabled: yes
